### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by ScullWM** [mmoreram/translation-server#8]
Hi,

I've fork this project and made some different kind of improvement (like export missing translation keys per languages) and have planed others (like sending them to a i18n api/server).
I've some issues testing it so I've try to compile a new phar, but bin/compile no longer exist, and the old version seems not work.

Is it still possible to compile project to phar ? Is there a tricky thing to do ?

Thanks, great potential for this repos!

**Comment by mmoreram** [comment]
Hmmm, checking it...

**Comment by mmoreram** [comment]
Done!

I've created this PR - https://github.com/mmoreram/translation-server/pull/9
Can you try it and provide me some feedback?

About your new features, don't hesitate to propose them to this project, so we can review them and add them here!

^^ Thanks!

**Comment by ScullWM** [comment]
Thanks, I will try this soon and tell you how it work. 
Actually my features tests are on my fork (branch dev_dump).
https://github.com/ScullWM/translation-server/tree/dev_dump

**Comment by ScullWM** [comment]
I've just try and I get my custom phar file. Just the build cmd was missing in the readme. 
Thanks ;)
